<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2DZnCPx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2DZnCPx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2DZnCPx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2DZnCPx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2DZnCPx\App_KernelDevDebugContainer([
    'container.build_hash' => '2DZnCPx',
    'container.build_id' => 'b72e57ad',
    'container.build_time' => 1694591642,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2DZnCPx');
